spring:
  security:
    oauth2:
      client:
        registration:
          local-sas:
            provider: local-sas
            client-id: messaging-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/messaging-client-oidc"
            scope: openid
        provider:
          local-sas:
            issuer-uri: http://auth-server:9000
