spring:
  security:
    oauth2:
      client:
        registration:
          auth-client:
            provider: auth-server
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/messaging-client-oidc
            scope: openid
        provider:
          auth-server:
            issuer-uri: ${ISSUER_URI}
  #autoconfigure:
  #  exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration
